<div class="content">
<?php View::content();?>
<h3>Editar equipo</h3>
<?php echo Form::open(); 
	?>
    <label>Serie
    <?php echo Form::text('equipos.serie') ?></label>
	<label>Tipo
	<?php echo Form::text('equipos.tipo') ?></label>
    <label>Telefono
    <?php echo Form::dbSelect('equipos.lineas_id','sim')?></label>
    <label>Imei
    <?php echo Form::text('equipos.imei') ?></label>
    <?php echo Form::hidden('equipos.id') ?>
    <?php echo Form::submit('Actualizar') ?>
<?php echo Form::close(); ?>
</div>